language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install Django~=$DJANGO
  - pip install -r requirements-dev.txt
  - python setup.py develop
env:
  - DJANGO="1.7"
  - DJANGO="1.8"
  - DJANGO="1.9"
  - DJANGO="1.10"
  - DJANGO="1.11"
script: py.test
matrix:
    exclude:
       - python: "3.3"
         env: DJANGO="1.9"
         env: DJANGO="1.10"
         env: DJANGO="1.11"
       - python: "3.5"
         env: DJANGO="1.7"
       - python: "3.6"
         env: DJANGO="1.7"
         env: DJANGO="1.8"
         env: DJANGO="1.9"
         env: DJANGO="1.10"  
